ruby/config/routes.rb
KeywordMonk::Application.routes.draw do  
  match "/download" => "downloads#download"
  
  namespace :api do
    namespace :v1 do
      match 'verify_installation' => 'users#verify_installation',  :via => :get

      resources :links, :only => [:create, :destroy, :index]
      resources :users, :only => [:create] do        
        get 'register', :on => :collection
      end

      resources :sessions, :only => [:create, :destroy] do 
         match 'logout' => 'sessions#destroy', :via => [:get, :delete], :on => :collection
      end
    end
  end

  namespace :business do
    match 'request_invite' => 'invites#new', :via => :get, :as => 'request_invite'    
    match '/invites' => "invites#create", :via => :post

    resources :sessions, :only => [:new, :create, :destroy] do
      match 'logout' => 'sessions#destroy', :via => [:get, :delete], :on => :collection
    end
    
    resources :users, :only => [:new, :create] do
      get 'register', :on => :collection
      member do 
        get 'dashboard'
      end
      resources :monitored_uris, :only => [:new, :create, :destroy]     
    end

  end

  root :to => "downloads#download"

end

ruby/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                 :integer          not null, primary key
#  name               :string(255)
#  encrypted_password :string(255)
#  email              :string(255)      default(""), not null
#  plugin_key         :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  salt               :string(255)
#  roles_mask         :integer
#

class User < ActiveRecord::Base
    #include RoleModel

    #constants
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  	attr_accessor :password, :password_confirmation
  	attr_accessible :email, :name, :password, :password_confirmation		

    #associations
    has_many :links

  	#validations
  	validates :email, :presence => true,
  					  :format => {:with => VALID_EMAIL_REGEX}
    validates_uniqueness_of :email, :scope => :role
    validates_presence_of :role  			

  	validates_presence_of :password, :password_confirmation, :on => :create
  	validates_presence_of :name
    validates_presence_of :plugin_key, :message => "Please ensure plugin is installed and enabled and refersh this page.", :if => Proc.new {|user| user.role == 'PLUGIN'}
    validates_uniqueness_of :plugin_key, :scope => :email, :if => Proc.new{|user| user.role == 'PLUGIN'}

  	validate :password_matches_confirmation?, :on => :create  	

    #hooks
    before_create :generate_crypted_password

    # plugin user, business user and admin user

  	def password_matches_confirmation?
  		self.password == self.password_confirmation
  	end

  	def generate_crypted_password
  		self.salt = ::BCrypt::Engine.generate_salt(10)
  		self.encrypted_password = encrypt_password(self.password, self.salt)
  	end

  	def authenticate
  		(self.encrypted_password == encrypt_password(self.password, self.salt))
  	end

  private  

  	def encrypt_password(password, salt)  	
  		encrypted_password = ::BCrypt::Engine.hash_secret(self.password, salt)  	  	
  	end
end

ruby/app/controllers/business/invites_controller.rb
class Business::InvitesController < ApplicationController
  def new
  	render :layout => 'layouts/downloads_layout'
  end

  def create 
  	email = params[:email]  	
  	invites_api = Services::Invite.new(email)
  	response = invites_api.create
  	respond_to do |format|  		
	  	if response['status'] == 'success'
	  		format.json {
  				render :json => {:status => 'success'}	
  			}
  			format.html{}
  		elsif response['status'] == 'error' && response['errors']['email'].include?("has already been taken")
  			format.json {
  				render :json => {:status => 'success'}	
  			}
  			format.html{}
  		else
  			format.json {
  				render :json => {:status => 'error', :errors => "#{response['errors'].keys.first} #{response['errors'].values.join(', ')}" }
  			}
  			format.html{}
	  	end
	  end
  end
end

ruby/app/controllers/business/users_controller.rb
class Business::UsersController < ApplicationController
  def new
  end

  def register
  	@business_user = BusinessUser.new
  end

  def create
  	binding.pry
  	@business_user = BusinessUser.new(params[:business_user])
  	if @business_user.save
  		flash[:notice] = "Account has been successfully created."
  		warden.set_user(@business_user)
  		redirect_to dashboard_business_user_url(@business_user)
  	else
  		flash.now[:error] = "Please fix the following errors to complete the account creation process."
  		render :register
  	end
  end

  def dashboard
  end
end

ruby/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :register
  end

  def register
    @user = User.new    
  end

  def create    
    @user = User.new(params[:user])
    @user.plugin_key = params[:plugin_key] if params[:plugin_key].present?
    @pk = params[:plugin_key]    
    @user.role = "PLUGIN"    

    if @user.save            
      warden.set_user(@user)
      redirect_to root_url, :notice => "Sign up was successful"
    else
      flash.now[:error] = "Sign up could not be completed"
      render :register
    end
  end

  def verify_installation    
  end

  def edit
  end

  def update
  end

  def show
  end

  def destroy
  end
end

ruby/app/helpers/business/invites_helper.rb
module Business::InvitesHelper
end

ruby/app/helpers/business/users_helper.rb
module Business::UsersHelper
end

ruby/app/helpers/users_helper.rb
module UsersHelper
end

ruby/app/views/business/users/dashboard.html.erb
<h1> <%= current_user.name %>'s Dashboard </h1>
<p> Organize your company dashboard </p>

ruby/app/views/business/users/new.html.erb
<h1>Business::Users#new</h1>
<p>Find me in app/views/business/users/new.html.erb</p>

ruby/app/views/business/users/register.html.erb
<div class="page-header">
  <h1> Signup <small> Find out how your competitors target audiences differently. </small>
</div>
<%= form_for @business_user, :as => :business_user, :url => business_users_url, :method => :post,  :html => {:class => 'form-horizontal'} do |f| %>
  <%= render :partial => "users/error_messages", :locals => {:user => @business_user} %>

  <div class="control-group">
    <label class="control-label" for="inputEmail">Name</label>
    <div class="controls">      
      <%= f.text_field :name, :placeholder => "Name" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputEmail">Email</label>
    <div class="controls">      
      <%= f.text_field :email, :placeholder => "Email" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password</label>
    <div class="controls">      
      <%= f.password_field :password, :placeholder => "Password" %>
    </div>
  </div>
  <div class="control-group">
    <label class="control-label" for="inputPassword">Password Confirmation</label>
    <div class="controls">      
      <%= f.password_field :password_confirmation, :placeholder => "Password Confirmation" %>
    </div>
  </div>
  <div class="control-group">
    <div class="controls">    
      <button type="submit" class="btn btn-primary">Register</button>
    </div>
  </div>
<% end %>