ruby/config/routes.rb
KeywordMonk::Application.routes.draw do  
  match "/download" => "downloads#download"
  
  namespace :api do
    namespace :v1 do
      match 'verify_installation' => 'users#verify_installation',  :via => :get

      resources :links, :only => [:create, :destroy, :index]
      resources :users, :only => [:create] do        
        get 'register', :on => :collection
      end

      resources :sessions, :only => [:create, :destroy] do 
         match 'logout' => 'sessions#destroy', :via => [:get, :delete], :on => :collection
      end
    end
  end

  namespace :business do
    match 'request_invite' => 'invites#new', :via => :get, :as => 'request_invite'    
    match '/invites' => "invites#create", :via => :post

    resources :sessions, :only => [:new, :create, :destroy] do
      match 'logout' => 'sessions#destroy', :via => [:get, :delete], :on => :collection
    end
    
    resources :users, :only => [:new, :create] do
      get 'register', :on => :collection
      member do 
        get 'dashboard'
      end
      resources :monitored_uris, :only => [:new, :create, :destroy]     
    end

  end

  root :to => "downloads#download"

end

ruby/app/views/shared/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top">
	<div class="navbar-inner">
        <div class="container">
    	      	<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        		    <span class="icon-bar"></span>
            		<span class="icon-bar"></span>
            		<span class="icon-bar"></span>
          		</button>
          		<%= link_to "Keyword Monk", api_v1_links_url, :class => 'brand' %>
          		<div class="nav-collapse collapse">
            		<ul class="nav" style="float:right;">
                  <% if current_user.present? %>
                    <li class="">
                      <%= link_to "Logout", logout_api_v1_sessions_url, :method => :delete %>
                    </li>              			
                  <% else %>
                    <li class="">
                      <%= link_to "Request Invites", business_request_invite_url %>
                    </li>              
                  <% end %>      
            		</ul>
          		</div>
        </div>
    </div>
</div>